### ISSUE TITLE
Need project-specific config options

### ISSUE THREAD

**Issue by banderon** [Chassis/SequelPro#10]
`vagrant sequel` attempts to SSH into `127.0.0.1` and use a key file.

<img width="394" alt="Screen Shot 2020-04-03 at 19 41 48" src="https://user-images.githubusercontent.com/533529/78412907-31197780-75e3-11ea-87d0-149e7baea3b4.png">

Our configuration has a custom IP set... and and we don't have a key, we just use the default vagrant password (`vagrant`).

As such, the CLI command doesn't work. We need to manually set the proper fields to get access:
<img width="443" alt="Screen Shot 2020-04-03 at 19 38 03" src="https://user-images.githubusercontent.com/533529/78412807-bfd9c480-75e2-11ea-84da-31c0907b1f59.png">

Are these fields manually configurable via yaml file? If so, could you update the readme to include specifics of the syntax?

Or better yet, can you just pull that data from the config used in the current vagrant?

**Comment by BronsonQuick** [comment]
Hey @banderon, thanks for the issue! We do generate those from a yaml file but as you noted we haven't included that information in the readme so I'll do a Pull Request and update that.

**Comment by BronsonQuick** [comment]
Hey @banderon, turns out those options weren't as configurable as I thought so I've added some code to handle that now and updated that readme for you. Let me know if you have any trouble or hit any bugs! Thanks again for the issue!

**Comment by banderon** [comment]
Thanks for the very quick turnaround! I'll give the new info a try.

**Comment by banderon** [comment]
Thanks for the very quick turnaround @BronsonQuick ! I'll give the new info a try.

**Comment by banderon** [comment]
Our only difference from the default setup was setting a custom `ip`. For anyone else that stumbles upon this, we have this working now with the following config:
```yaml
# Use DHCP to dynamically assign IP addresses on the private network.
ip: 10.1.2.3

# Configure SSH connection for SequelPro
ssh:
  host: 10.1.2.3
  user: vagrant
  port: 22
  private_key_path:
    - ~/.vagrant.d/boxes/chassis-VAGRANTSLASH-chassis/3.0.3/virtualbox/vagrant_private_key
```

**Comment by BronsonQuick** [comment]
@banderon Ahh awesome. Thanks. I figured you must've set the IP manually but I wasn't sure. I'll update the docs to add some information about that too. Thank you Sir!

**Comment by kadamwhite** [comment]
Note for future listeners: as of 78d88b8 / #14 the `ssh:` section will fall back to defaults if any property is omitted, and `host` will fall back to the top-level `ip`, so the example in @banderon's comment above could be simplified to
```yaml
ip: 10.1.2.3

ssh:
  port: 22
```
