### ISSUE TITLE
SSH host is populated as `dhcp`

### ISSUE THREAD

**Issue by dashaluna** [Chassis/SequelPro#16]
Hello,

I've installed the sequel extension as a global extension (and it's currently the only global extension that I've got). I run the command and here's what I've got in the SequelPro screen that opened up:

<img width="1011" alt="chassis sequel" src="https://user-images.githubusercontent.com/2185972/86374104-16a37880-bc7c-11ea-9996-02256228dccb.png">

SSH host was set to `dhcp`. A colleague of mine helped me saying that it should be `127.0.0.1` which worked.

I wanted to report this in case it's a bug that could be fixed. Otherwise, for people who just starting out with chassis & VMs in general, perhaps it's worth adding a note to read me to replace the `dhcp` string with SSH host, that in turn could be looked up doing `vagrant  ssh-config`.

Thanks!

1. What operating system do you use?
Mac OS

2. What version of Vagrant are you running?
2.2.9

3. Are you using VirtualBox or VMWare and which version are you using?
VirtualBox 6.1.10

4. Do you have a custom YAML file? If so, what does it contain?
```
paths:
    base: ..
    content: content
    wp: wordpress
hosts:
    - site-name.local
site:
    name: Platform Reveal
multisite: Yes

extensions:
    - nodejs
    - cavalcade
    - tachyon
    - composer
    - npm
    - shadyvb/chassis-redis

php: 7.2
```

5. Do you have any Chassis other extensions installed? If so, what are they?
See above ^.
